// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKuYDIaMwI0DQNCUL7Yw63ZxdKMmOII5E',
    appId: '1:497055047812:web:c79d056a9f7e6d931ae2d1',
    messagingSenderId: '497055047812',
    projectId: 'eazyshop-10643',
    authDomain: 'eazyshop-10643.firebaseapp.com',
    storageBucket: 'eazyshop-10643.firebasestorage.app',
    measurementId: 'G-5TW42T4W2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDndaV7_wFLSfChOYrZXJOnJ7lGR59xKuE',
    appId: '1:497055047812:android:00a02f1ba7bd67ac1ae2d1',
    messagingSenderId: '497055047812',
    projectId: 'eazyshop-10643',
    storageBucket: 'eazyshop-10643.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaclS6jk0UmBn212_hTEN16VMIVABJZmI',
    appId: '1:497055047812:ios:e31b1476a545be361ae2d1',
    messagingSenderId: '497055047812',
    projectId: 'eazyshop-10643',
    storageBucket: 'eazyshop-10643.firebasestorage.app',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaclS6jk0UmBn212_hTEN16VMIVABJZmI',
    appId: '1:497055047812:ios:e31b1476a545be361ae2d1',
    messagingSenderId: '497055047812',
    projectId: 'eazyshop-10643',
    storageBucket: 'eazyshop-10643.firebasestorage.app',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKuYDIaMwI0DQNCUL7Yw63ZxdKMmOII5E',
    appId: '1:497055047812:web:fb982ad3ffed1f171ae2d1',
    messagingSenderId: '497055047812',
    projectId: 'eazyshop-10643',
    authDomain: 'eazyshop-10643.firebaseapp.com',
    storageBucket: 'eazyshop-10643.firebasestorage.app',
    measurementId: 'G-216TBR2402',
  );
}
